<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Photo', 'doctrine');

/**
 * BasePhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $file_name
 * @property string $title
 * @property boolean $live
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method string  getFileName()  Returns the current record's "file_name" value
 * @method string  getTitle()     Returns the current record's "title" value
 * @method boolean getLive()      Returns the current record's "live" value
 * @method Photo   setId()        Sets the current record's "id" value
 * @method Photo   setFileName()  Sets the current record's "file_name" value
 * @method Photo   setTitle()     Sets the current record's "title" value
 * @method Photo   setLive()      Sets the current record's "live" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('photo');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('file_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('live', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}