<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SpecialOffer', 'doctrine');

/**
 * BaseSpecialOffer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $description_one
 * @property string $description_two
 * @property string $description_three
 * @property integer $display_order
 * @property boolean $front_page
 * @property boolean $live
 * 
 * @method integer      getId()                Returns the current record's "id" value
 * @method string       getDescriptionOne()    Returns the current record's "description_one" value
 * @method string       getDescriptionTwo()    Returns the current record's "description_two" value
 * @method string       getDescriptionThree()  Returns the current record's "description_three" value
 * @method integer      getDisplayOrder()      Returns the current record's "display_order" value
 * @method boolean      getFrontPage()         Returns the current record's "front_page" value
 * @method boolean      getLive()              Returns the current record's "live" value
 * @method SpecialOffer setId()                Sets the current record's "id" value
 * @method SpecialOffer setDescriptionOne()    Sets the current record's "description_one" value
 * @method SpecialOffer setDescriptionTwo()    Sets the current record's "description_two" value
 * @method SpecialOffer setDescriptionThree()  Sets the current record's "description_three" value
 * @method SpecialOffer setDisplayOrder()      Sets the current record's "display_order" value
 * @method SpecialOffer setFrontPage()         Sets the current record's "front_page" value
 * @method SpecialOffer setLive()              Sets the current record's "live" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpecialOffer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('special_offer');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('description_one', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description_two', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description_three', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('display_order', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('front_page', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('live', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}