<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Product', 'doctrine');

/**
 * BaseProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property decimal $price
 * @property boolean $is_available
 * @property integer $category_id
 * @property string $extra_info
 * 
 * @method integer getId()           Returns the current record's "id" value
 * @method string  getName()         Returns the current record's "name" value
 * @method decimal getPrice()        Returns the current record's "price" value
 * @method boolean getIsAvailable()  Returns the current record's "is_available" value
 * @method integer getCategoryId()   Returns the current record's "category_id" value
 * @method string  getExtraInfo()    Returns the current record's "extra_info" value
 * @method Product setId()           Sets the current record's "id" value
 * @method Product setName()         Sets the current record's "name" value
 * @method Product setPrice()        Sets the current record's "price" value
 * @method Product setIsAvailable()  Sets the current record's "is_available" value
 * @method Product setCategoryId()   Sets the current record's "category_id" value
 * @method Product setExtraInfo()    Sets the current record's "extra_info" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('price', 'decimal', 20, array(
             'type' => 'decimal',
             'length' => 20,
             'scale' => '2',
             ));
        $this->hasColumn('is_available', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('category_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('extra_info', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}