<?php

/**
 * CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
    /**
     * function getInstance()
     * ----------------------
     * Returns an instance of this class.
     *
     * @return object CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Category');
    }

    /**
     * function getCategories()
     * ------------------------
     * fetch the categories
     *
     * @return mixed DoctrineCollection or boolean
     */
    public static function getCategories()
    {
        // build the DQL
        $q = Doctrine_Core::getTable('Category')->createQuery('c');
        $q->orderBy('c.display_order ASC');

        // run the query
        $categories = $q->execute();

        // build up the category array
        foreach($categories as $category) {
            $category_ar[$category->getId()] = $category->getName();
        }

        // return the categories if we have some
        if(count($category_ar)>0) {
            return $category_ar;
        } else {
            return false;
        }
    }

    /**
     * function getCategoriesById($id)
     * -------------------------------
     * fetch the categories by id
     *
     * @param int $id
     * @return mixed DoctrineCollection or boolean
     */
    public static function getCategoriesById($id)
    {
        // build the DQL
        $q = Doctrine_Core::getTable('Category')->createQuery('c');
        $q->addWhere('c.id = "'.$id.'"');
        $q->orderBy('c.display_order ASC');

        // execute the DQL
        $categories = $q->execute();

        // if there are categories then return them otherwise return false
        if($categories->count()>0) {
            return $categories;
        } else {
            return false;
        }
    }

    /**
     * function getCategoriesByTreatmentGroupId($treatment_group_id)
     * -------------------------------------------------------------
     * fetch the categories by the treatment group id
     *
     * @param int $treatment_group_id
     * @return mixed DoctrineCollection or boolean
     */
    public static function getCategoriesByTreatmentGroupId($treatment_group_id)
    {
        // build the DQL
        $q = Doctrine_Core::getTable('Category')->createQuery('c');
        $q->addWhere('c.treatment_group_id = "'.$treatment_group_id.'"');
        $q->orderBy('c.display_order ASC');

        // execute the DQL
        $categories = $q->execute();
        
        //if there are categories then return them otherwise return false
        if($categories->count()>0) {
            return $categories;
        } else {
            return false;
        }
    }
}