<?php

/**
 * FacebookAlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FacebookAlbumTable extends Doctrine_Table
{
    /**
    * Returns an instance of this class.
    *
    * @return object FacebookAlbumTable
    */
    public static function getInstance()
    {
       return Doctrine_Core::getTable('FacebookAlbum');
    }

    /**
     * function getAlbumCount()
     * ------------------------
     * get a count of facebook albums
     *
     * @return mixed int count of albums / boolean no albums
     */
    public static function getAlbumCount()
    {
        // build the DQL
        $f = Doctrine_Core::getTable('FacebookAlbum')->createQuery('f');
        $fb_albums = $f->execute();

        // return the count or if none, then return false
        if($fb_albums->count() > 0) {
            return $fb_albums->count();
        } else {
            return false;
        }
    }

    /**
     * function getAlbumByFbId()
     * -------------------------
     * get an album by facebook id
     * 
     * @param int $fb_id
     * @return
     */
	public static function getAlbumByFbId($fb_id) 
	{
        // build the DQL
		$f = Doctrine_Core::getTable('FacebookAlbum')->createQuery('f');		
		$f->addWhere("f.fb_id = '".$fb_id."'");

        // execute the DQL
		$album = $f->execute();

        // if there are albums then return them, otherwise return false
		if($album->count()>0) {
			return $album->getFirst();
		} else {
			return false;
		}
	}	
}