<?php

/**
 * FacebookAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FacebookAlbum extends BaseFacebookAlbum
{
    // populate the object member variables
	public function setFields($data)
	{
		if(!empty($data['id'])) { $this->setFbId($data['id']); }
		if(!empty($data['name'])) { $this->setName($data['name']); }		
		if(!empty($data['link'])) { $this->setLink($data['link']); }				
		if(!empty($data['cover_photo'])) { $this->setCoverPhoto($data['cover_photo']); }						
		if(!empty($data['count'])) { $this->setPhotoCount($data['count']); }						
		if(!empty($data['type'])) { $this->setType($data['type']); }						
		if(!empty($data['created_time'])) { $this->setFbCreatedTime($data['created_time']); }								
		if(!empty($data['updated_time'])) { $this->setFbUpdatedTime($data['updated_time']); }								
		if(!empty($data['comments']['data'])) { $this->setNumComments(count($data['comments']['data'])); }								
		if(!empty($data['live_in_photos'])) { $this->setLiveInPhotos($data['live_in_photos']); }								
	}
}