<?php

/**
 * FacebookPhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FacebookPhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FacebookPhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FacebookPhoto');
    }

    /**
     * function getPhotoByFbId($fb_id)
     * -------------------------------
     * fetch all the photos by facebook id
     *
     * @param int $fb_id
     * @return mixed DoctrineCollection list of fb photos / boolean no photos
     */
    public static function getPhotoByFbId($fb_id)
    {
        $f = Doctrine_Core::getTable('FacebookPhoto')->createQuery('f');
        $f->addWhere("f.fb_id = '".$fb_id."'");

        $photo = $f->execute();

        if($photo->count()>0) {
            return $photo->getFirst();
        } else {
            return false;
        }
    }

    /**
     * function getFrontpagePhotos()
     * -----------------------------
     * fetch all the photos for the front page
     *
     * @return mixed DoctrineCollection list of fb photos / boolean no photos
     */
    public static function getFrontpagePhotos()
    {
        $f = Doctrine_Core::getTable('FacebookPhoto')->createQuery('f');
        $f->addWhere("f.live_on_homepage = '1'");

        $front_photos = $f->execute();

        if($front_photos->count()>0) {
            return $front_photos;
        } else {
            return false;
        }
    }
}