<?php

/**
 * MailingListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailingListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MailingListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MailingList');
    }
}