<?php

/**
 * PhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhotoTable extends Doctrine_Table
{
    /**
     * function getInstance()
     * ----------------------
     * Returns an instance of this class.
     *
     * @return object PhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Photo');
    }

    /**
     * function getPhotos()
     * --------------------
     * fetch all the live photos for the frontend
     *
     * @param int $limit
     * @return mixed DoctrineCollection of photos / boolean no photos
     */
	public static function getPhotos($limit="")
	{
        // build the DQL
		$q = Doctrine_Core::getTable('Photo')->createQuery('p');
		$q->addWhere('p.live=1');

		// add the limit if needed
		if($limit!=""){
			$q->limit($limit);			
		}

        // execute the DQL
		$photos = $q->execute();
		if($photos->count()>0) {
			return $photos;
		} else {
			return false;
		}				
	}
}