<?php

/**
 * Photo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Photo extends BasePhoto
{
    /**
     * function hasThumbnail()
     * -----------------------
     * checks whether a thumbnail version exists
     * @return boolean
     */
	public function hasThumbnail()
	{
		if(is_file(sfConfig::get('sf_upload_dir').'/1_'.$this->getFileName())) {
			return true;
		} else {
			return false;
		}
	}

	/**
     * function getThumbnail()
     * -----------------------
     * return the path to the thumbnail
     *
     * @return string path to the thumbnail
     */
	public function getThumbnail()
	{
		return '/uploads/4_'.$this->getFileName();
	}

    /**
     * function getPhoto()
     * -------------------
     * return the path to the photo
     *
     * @return string path to the thumbnail
     */
	public function getPhoto()
	{
		return '/uploads/'.$this->getFileName();		
	}

    /**
     * function getGalleryPhotoBySize($size="")
     * ----------------------------------------
     * wrapper to fetch the different size photos for the gallery
     *
     * @param size of photo $size
     * @return string
     */
	public function getGalleryPhotoBySize($size="")
	{
		$location= '/uploads/'.$size.'_'.$this->getFileName();
		return $location;				
	}

    /**
     * function getFrontendPhoto($size="")
     * -----------------------------------
     * return the HTML for a given image in the frontend
     *
     * @param string $size
     */
	public function getFrontendPhoto($size="")
	{
		if($size!="") {
			 echo "<img src='".$this->getGalleryPhotoBySize($size)."'/>";
		} else {
			 echo "<img src='".$this->getPhoto()."'/>";			
		}
	}

    /**
     * function getBackendPhoto()
     * --------------------------
     * return the HTML for a given image in the backend
     * 
     * @param string $size
     */
	public function getBackendPhoto()
	{
		if($this->hasThumbnail()) {
			 echo "<img src='".$this->getThumbnail()."'/>";
		} else {
			 echo "<img src='".$this->getPhoto()."'/>";			
		}
	}
}