<?php

/**
 * Product
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Product extends BaseProduct
{
    /**
     * function getPriceBackend()
     * --------------------------
     * format the price for the backend
     *
     * @return string price for listing in the backend
     */
	public function getPriceBackend()
	{
		return "€".$this->getPrice();
	}

    /**
     * function getCategoryName()
     * --------------------------
     * fetch the category this product is within
     *
     * @return object Category object
     */
	public function getCategoryName()
	{
		return self::getCategory()->getName();
	}

    /**
     * function hasExtraInfo()
     * -----------------------
     * checks whether there is extra info for this product
     * 
     * @return boolean - whether this product has extra info or not
     */
	public function hasExtraInfo()
	{
		if(strlen($this->getExtraInfo())>0) {
			return true;
		} else {
			return false;			
		}
	}

    /**
     * function getCategory()
     * ----------------------
     * return the category this product is within
     *
     * @return object Category object
     */
	public function getCategory()
	{
        // build the filter
        $where = 'c.id = '.$this->getCategoryId();

        // build the DQL
		$q = Doctrine_Core::getTable('Category')->createQuery('c')
											 	->addWhere($where);
		// execute the DQL
		$category = $q->execute()->getFirst();

        // return the category
		return $category;	
	}	
}
