<?php

/**
 * SpecialOfferTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpecialOfferTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpecialOfferTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SpecialOffer');
    }

    /**
     * function getSpecialOffers($limit="", $frontpage="")
     * ---------------------------------------------------
     * fetch all the special offers
     *
     * @param int $limit
     * @param boolean $frontpage
     * @return mixed DoctrineCollection of SpecialOffers / boolean no offers
     */
	public static function getSpecialOffers($limit="", $frontpage="")
	{
        // build the DQL
		$q = Doctrine_Core::getTable('SpecialOffer')->createQuery('s');

        // add the front page filter
		if($frontpage){
			$q->addWhere('s.front_page=1');
		}

        // add the rest of the filters
		$q->addWhere('s.live=1');

        // add the order by criteria
		$q->orderBy('s.display_order ASC');

        // add the limit filter if need be
		if($limit!=""){
			$q->limit($limit);			
		}

        // execute the offers
		$offers = $q->execute();

        // if there are offers, then return them otherwise return false
		if($offers->count()>0) {
			return $offers;
		} else {
			return false;
		}				
	}
}