<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TreatmentGroup', 'doctrine');

/**
 * BaseTreatmentGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $display_order
 * 
 * @method integer        getId()            Returns the current record's "id" value
 * @method string         getName()          Returns the current record's "name" value
 * @method integer        getDisplayOrder()  Returns the current record's "display_order" value
 * @method TreatmentGroup setId()            Sets the current record's "id" value
 * @method TreatmentGroup setName()          Sets the current record's "name" value
 * @method TreatmentGroup setDisplayOrder()  Sets the current record's "display_order" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTreatmentGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('treatment_group');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('display_order', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}