<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Testimonial', 'doctrine');

/**
 * BaseTestimonial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $statement
 * @property string $name
 * @property integer $display_order
 * @property boolean $live
 * 
 * @method integer     getId()            Returns the current record's "id" value
 * @method string      getStatement()     Returns the current record's "statement" value
 * @method string      getName()          Returns the current record's "name" value
 * @method integer     getDisplayOrder()  Returns the current record's "display_order" value
 * @method boolean     getLive()          Returns the current record's "live" value
 * @method Testimonial setId()            Sets the current record's "id" value
 * @method Testimonial setStatement()     Sets the current record's "statement" value
 * @method Testimonial setName()          Sets the current record's "name" value
 * @method Testimonial setDisplayOrder()  Sets the current record's "display_order" value
 * @method Testimonial setLive()          Sets the current record's "live" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTestimonial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('testimonial');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('statement', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('display_order', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('live', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}