<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Category', 'doctrine');

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $display_order
 * @property string $extra_info
 * @property integer $treatment_group_id
 * 
 * @method integer  getId()                 Returns the current record's "id" value
 * @method string   getName()               Returns the current record's "name" value
 * @method integer  getDisplayOrder()       Returns the current record's "display_order" value
 * @method string   getExtraInfo()          Returns the current record's "extra_info" value
 * @method integer  getTreatmentGroupId()   Returns the current record's "treatment_group_id" value
 * @method Category setId()                 Sets the current record's "id" value
 * @method Category setName()               Sets the current record's "name" value
 * @method Category setDisplayOrder()       Sets the current record's "display_order" value
 * @method Category setExtraInfo()          Sets the current record's "extra_info" value
 * @method Category setTreatmentGroupId()   Sets the current record's "treatment_group_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('display_order', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('extra_info', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('treatment_group_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}