<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/11/20 16:53:40

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bbs',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
